project:
  type: book
  output-dir: _book
  render:
    - index.qmd
    - week01-practice.qmd
    - grand-canonical.qmd
    - identical-particles.qmd
    - quantum-distributions.qmd
    - bose-einstein-condensation.qmd
    - fermi-gas-ground-state.qmd
    - fermi-gas-heat-capacity.qmd
    - fermi-gas-pauli.qmd
    - phase-transitions.qmd
    - ising-mean-field.qmd
    - landau-second-order.qmd
    - landau-first-order.qmd
    - ising-exact-1d.qmd

lang: ja

book:
  title: "統計力学II 2026"
  author: "品岡寛"
  chapters:
    - index.qmd
    - week01-practice.qmd
    - grand-canonical.qmd
    - identical-particles.qmd
    - quantum-distributions.qmd
    - bose-einstein-condensation.qmd
    - fermi-gas-ground-state.qmd
    - fermi-gas-heat-capacity.qmd
    - fermi-gas-pauli.qmd
    - phase-transitions.qmd
    - ising-mean-field.qmd
    - landau-second-order.qmd
    - landau-first-order.qmd
    - ising-exact-1d.qmd

format:
  html:
    theme: cosmo
    html-math-method: mathjax
    number-sections: false
